### ISSUE TITLE
Webhook URL not generating

### ISSUE THREAD

**Issue by smtpstn** [blopa/Magento-Chatbot#31] opened 2017-03-28 08:39 UTC
Hello, 

I have setup your extension for Facebook Chat Bot. I have filled all the information. Now I am facing problem in accessing the url with custom key.

When I try to hit **https://www.techgetgo.com/chatbot/chatdata/facebook/key/4574er5ehiy/** I receive the following message.

**To configure Facebook webhook access https://developers.facebook.com/apps/(FACEBOOK_APP_ID)/webhooks/ and set the webhook URL as https://www.techgetgo.com/chatbot/chatdata/facebook/key/4574er5ehiy/**

After this when I go to FB developer interface and try to setup the webhook URL I receive the error message. Please check the screenshot below.

![fbb](https://cloud.githubusercontent.com/assets/26736002/24396316/609d6648-13c0-11e7-9663-67c82cf5d566.png)

Now please tell me which configuration I am missing. 

Thanks

**Comment by blopa** [comment] 2017-03-28 11:58
Hello smtpstn,

I'm really sorry about this. I'm working in a better documentation for this extension. Your verify token must be the same as you custom key, so in this case must be "4574er5ehiy". I didn't thought it was necessary to have multiple keys for multiple purposes, that's why I simplify by using this one "custom key".

Could you try that and let me know?

Best.

**Comment by smtpstn** [comment] 2017-03-29 05:39
Hello,

Thanks for the quick response.

I have changed my verify token to my custom key now WebHook  is setup on Facebook. Please check the below SS:
![ff](https://cloud.githubusercontent.com/assets/26736002/24440004/3bdadde0-146f-11e7-8d22-8bfc9a6cac43.png)

But still I am getting the same message **To configure Facebook webhook access https://developers.facebook.com/apps/(FACEBOOK_APP_ID)/webhooks/ and set the webhook URL as https://www.techgetgo.com/chatbot/chatdata/facebook/key/4574er5ehiy/** When I am trying to access the URL: **https://www.techgetgo.com/chatbot/chatdata/facebook/webhook/4574er5ehiy/**


Can you please let me know where I can access the chatbot?  I am not able to find any option where a user can access the chatbot? Also Is this chatbot can be accessed by a login user? OR anyone can use it?

If you guide me it would be great help for me.

Thanks.

**Comment by blopa** [comment] 2017-03-30 02:22
Hello!

Alright, here we go.

Q: Can you please let me know where I can access the chatbot? I am not able to find any option where a user can access the chatbot?
A: Your bot is available on Facebook chat, I guess that your bot is this one http://m.me/1441695065863926/, right?

Q: Also Is this chatbot can be accessed by a login user? OR anyone can use it?
A: This bot is only available for users logged on Facebook. But you can also setup a bot for Telegram aswell.

Best.

**Comment by smtpstn** [comment] 2017-03-30 05:11
Hello,

Thanks for providing the answers. I have tried by messaging to this bot but didn't received any auto reply.

Also How can I setup on my website so customer can directly interact with this.? Can I setup it as a Facebook Live chat support? Something  like this: https://marketplace.magento.com/yosto-module-facebook-messenger.html ?

I mean How our website user get to know about this functionality.  If you can help me It will be appreciated.

In waiting of your quick response.

Thanks

**Comment by blopa** [comment] 2017-03-30 12:09
Hello smtpstn,

I think that maybe you're missing some configuration on Facebook Developer website. My documentation is incomplete, I'll work on that the next weeks. Try following this tutorial starting from step #3: https://blog.hartleybrody.com/fb-messenger-bot/. You're probably missing the "Generate a Page Access Token" part.

As for the Facebook Live chat support, yeah, that would work. 

Best.

**Comment by blopa** [comment] 2017-03-30 12:10
Also, please be aware of step #7, because you'll need aproval from Facebook to use your bot to send messages to other users other than yourself.

**Comment by smtpstn** [comment] 2017-03-30 12:39
Hello,

Thanks for quick response.

I have created the page access token. Please check the below screenshot:
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/26736002/24504413/d9cd6d24-1573-11e7-8aea-bbc38cfba0d9.png)

After that I have tried to message bot via my own account, Still it's not replying. :(

Can you please tell me If I have to use this page access token somewhere in magento to get bot work?

Thanks

**Comment by blopa** [comment] 2017-03-30 12:49
Yes, you need to add this access token on the module backend configuration. Go to System > General Settings > Chatbot Settings

Please check this SS
https://raw.githubusercontent.com/blopa/Magento-Chatbot/master/screenshots/image_3.png

You'll have a lot to configure there, including commands code, enable/disable features, and many other things. This part is kind of documented on here: https://github.com/blopa/Magento-Chatbot

**Comment by smtpstn** [comment] 2017-03-30 13:04
Hello,
Thanks for quick response.

Please check below screenshot. Should I insert my page access token in this filed?

![fbm](https://cloud.githubusercontent.com/assets/26736002/24505446/8a5fa2ee-1577-11e7-8bc9-41f07959c44f.png)

**Comment by blopa** [comment] 2017-03-30 13:11
Yes, that's it :smile: 

I'm sorry about that. I'll change the text of this input and add better documentation.

Best

**Comment by smtpstn** [comment] 2017-03-30 13:20
Hello,

I have added my access token to that field. Still no reply from bot :(
![fbt](https://cloud.githubusercontent.com/assets/26736002/24506047/c460d02e-1579-11e7-91c1-e1795c8a1d8d.png)

**Comment by blopa** [comment] 2017-03-30 13:33
Can you send a SS of all your configuration for this module?

**Comment by smtpstn** [comment] 2017-03-30 13:40
Hello,

Please check below SS:

![fbms](https://cloud.githubusercontent.com/assets/26736002/24506849/74c6659e-157c-11e7-883b-94a8aa31decd.png)
![ge](https://cloud.githubusercontent.com/assets/26736002/24506850/74c75468-157c-11e7-8420-e6430166195f.png)

**Comment by blopa** [comment] 2017-03-30 13:57
That's weird. It should work. The problem is probably on Facebook Developer backend. 

Try checking other tutorials, or make another page just for testing, and follow that tutorial from step #2

**Comment by blopa** [comment] 2017-03-30 23:01
I'm gonna close this for now. If you have any other problems, please let us know!

**Closed as completed by blopa** 2017-03-30 23:01 UTC
